### ISSUE TITLE
Make this easier to run with Docker or K8s

### ISSUE THREAD

**Issue by Starttoaster** [PrettyCoffee/fluidity#16]
Proposal: Add a Dockerfile, make an official Docker image, and untether this from a GitHub Pages based installation. It may be possible to leave GitHub Pages as a secondary option, but I'm not sure if the `homepage` element in `package.json` is required for Pages as I switched that in my fork to `"./"`

Not sure what your appetite for that is, but Docker/K8s, or just baremetal, gives you much more control over things such as access control. Many people use kubernetes ingresses to expose their containerized services, and ingress controllers can place things like authentication or source IP whitelisting in front of your services to keep people you may not want seeing your dashboard away from it.

I've already put together a helm chart and Dockerfile that I've installed in my homelab, so I could help with this if you'd like. There may be some anti-patterns in my Dockerfile as I'm not a node developer. If there's no interest in this, that's fine, just close this Issue.

**Comment by PrettyCoffee** [comment]
I personally prefer hosting everything on Github pages, but I dont mind adding a Dockerfile.

If you are interested:
You wouldnt want to host it with a node image since running it with node is an unoptimized dev deployment.
With React and most other UI libraries, you will first want to build/compile your code into pure html/js and then host it via nginx.

My approach for a Dockerfile would be using a node container to build the webapp and then copy the build into an nginx container. The Docker build will probably take some time but this will result in the "most optimized" result.

I will let you know as soon as I added the Dockerfile if you want to have a look at it / test it :)

**Comment by Starttoaster** [comment]
> I personally prefer hosting everything on Github pages, but I dont mind adding a Dockerfile.
> 
> If you are interested: You wouldnt want to host it with a node image since running it with node is an unoptimized dev deployment. With React and most other UI libraries, you will first want to build/compile your code into pure html/js and then host it via nginx.
> 
> My approach for a Dockerfile would be using a node container to build the webapp and then copy the build into an nginx container. The Docker build will probably take some time but this will result in the "most optimized" result.
> 
> I will let you know as soon as I added the Dockerfile if you want to have a look at it / test it :)

Sure! In the meantime, if you would like to see my Dockerfile:

```
FROM node:18-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD nginx -g "daemon off;"
```

**Comment by PrettyCoffee** [comment]
The Dockerfile is added:
https://github.com/PrettyCoffee/fluidity/blob/main/Dockerfile

I also added some [documentation](https://github.com/PrettyCoffee/fluidity#docker-setup) to the readme.
