### ISSUE TITLE
Support with other search engines? 

### ISSUE THREAD

**Issue by DrNyaaa** [PrettyCoffee/fluidity#18]
I was able to get ecosia working pretty easily but I dont know how to use github and got stuck at the npm run deploy

**Comment by PrettyCoffee** [comment]
Did you fork the repo and setup `github pages` for it?
Furthermore, can you specify the problem more, do you have any error output or something? That would help a lot :)

**Comment by PrettyCoffee** [comment]
FYI: I added ecosia to fluidity now. https://github.com/PrettyCoffee/fluidity/commit/80205da825a68fcda5608a1a2fc0906602a55c24

But if you still are interested in working out how to set it up yourself, feel free to give me more info and I can have a look at the problem again :)

**Comment by DrNyaaa** [comment]
it seems like I forgot to fork the gh-pages branch and thanks for the implementation of ecosia

**Comment by DrNyaaa** [comment]
tho I would like to know how to add new themes as you can see below I was able to do it with index.html but unable with npm run start or gh pages 
![image](https://user-images.githubusercontent.com/99406142/186175476-5ae99baf-9431-42bf-afd0-dc561b855242.png)

**Comment by PrettyCoffee** [comment]
Wow, that rice looks awesome 🔥

Regarding the theme, my guess would be that this happens because all themes are saved in the local storage.
Initially, fluidity just copies the presets into the local storage and from there it always just edits them from there.
Since you probably changed the settings before, it has saved the old presets and ignored the new one.

The solution should be either pressing the `Delete all settings` button on the bottom right or, if you dont want to delete everything but only update the themes, deleting the `themes` key in the firefox devtools and then reloading the page:
![image](https://user-images.githubusercontent.com/66521452/186255560-89d4e7a3-4364-43a7-8065-024a7d5cb4e8.png)

That should do it :)
